version: "3.5"
services:
  agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc1
    container_name: agent-${JANUS_NAME}
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_GENESIS_URL: "http://dev.bcovrin.vonx.io/genesis"
      ACAPY_ENDPOINT: "http://agent-${JANUS_NAME}:${AGENT_PORT}"
      ACAPY_WEBHOOK_URL: "http://webhook-server:1080/agent-${JANUS_NAME}"
      ACAPY_LABEL: "${JANUS_NAME}"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_SEED: "pNyNR5AFXQv4O49VShGCM7jaaaGXLghb"
      ACAPY_WALLET_NAME: "wallet${JANUS_NAME}"
      ACAPY_WALLET_KEY: "walletkey"

    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_PORT} \
        --outbound-transport http \
        --admin '0.0.0.0' ${ADMIN_PORT}"
    ]
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"

  webhook-server:
    image: ghcr.io/timoglastra/acapy-development-webhook-server
    container_name: webhook-${JANUS_NAME}
    ports:
      - ${WEBHOOK_PORT}:1080
      # If using WSL you ill need to acess this throught the WSL network namve server. 
      # Get this using `cat /etc/resolv.conf`
      # http://172.20.64.1:${WEBHOOK_PORT}