version: "3.5"

services:
  controller:
    image: vitorestevamia/janus-controller:latest
    container_name: janus-controller
    command:
      [
        "/janus-controller",
        "--server-agent-ip",
        "agent"
      ]
    ports:
      - "${CONTROLLER_PORT}:8080"
    profiles:
      - issuer

  agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc1

    container_name: aca-py-${AGENT_NAME}
    environment:
      ACAPY_ENDPOINT: "${ENDPOINT}:${AGENT_PORT}"
      ACAPY_LABEL: "${AGENT_NAME}"

      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_LOG_LEVEL: "info"

      ACAPY_GENESIS_URL: "http://dev.bcovrin.vonx.io/genesis"
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_SEED: "${WALLET_SEED}"
      ACAPY_WALLET_NAME: "wallet${AGENT_NAME}"
      ACAPY_WALLET_KEY: "walletkey"

    entrypoint: /bin/bash
    command:
      [
        "-c",
        "aca-py start 
        --inbound-transport http '0.0.0.0' ${AGENT_PORT} 
        --outbound-transport http 
        --admin '0.0.0.0' ${ADMIN_PORT}
        --auto-accept-invites
        --auto-accept-requests
        --auto-ping-connection
        --auto-respond-credential-proposal
        --auto-respond-credential-offer
        --auto-respond-credential-request
        --auto-store-credential
        --auto-respond-presentation-proposal"
      ]
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
      - "${AGENT_PORT}:${AGENT_PORT}"
    depends_on:  #required while the image doesn't supports arm architecture
      - amd64_emulator
    profiles:
      - issuer
      - holder

  amd64_emulator: #required by now because of problems in multiplatform builds of aca-py
    container_name: amd64
    image: tonistiigi/binfmt
    privileged: true
    command: "--install amd64"  
    profiles:
      - holder