version: "3.5"

services:
  agent:
    platform: linux/amd64
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5

    container_name: acapy-agent
    environment:
      ACAPY_ENDPOINT: "http://${ENDPOINT}:${AGENT_PORT}"
      ACAPY_LABEL: "${AGENT_NAME}"

      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_LOG_LEVEL: "info"
      
      ACAPY_GENESIS_URL: "http://dev.bcovrin.vonx.io/genesis"
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_SEED: "${WALLET_SEED}"
      ACAPY_WALLET_NAME: "wallet${AGENT_NAME}"
      ACAPY_WALLET_KEY: "walletkey"

    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_PORT} \
        --outbound-transport http \
        --admin '0.0.0.0' ${ADMIN_PORT}"
    ]
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
      - "${AGENT_PORT}:${AGENT_PORT}"
